{{- if .Values.prometheus.ingress.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: monitoring
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/resource-policy": keep
type: Opaque
data:
  auth: {{ .Values.prometheus.ingress.basicAuth.auth }}
{{- end }}