---
  - name: Upgrade all packages to the latest version
    apt:
      upgrade: safe
      update_cache: yes
    become: yes

  - name: Install aptitude
    apt:
      name: aptitude
    become: yes
