apiVersion: v2
description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards, and Prometheus rules combined with documentation and scripts to provide easy to operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator.
engine: gotpl
type: application
name: kube-prometheus-stack
sources:
  - https://github.com/prometheus-community/helm-charts
  - https://github.com/prometheus-operator/kube-prometheus
version: 0.0.1
appVersion: 0.0.1
kubeVersion: ">=1.16.0-0"

dependencies:
- name: kube-state-metrics
  version: "2.9.*"
  repository: https://charts.helm.sh/stable
  condition: kubeStateMetrics.enabled
- name: prometheus-node-exporter
  version: "1.12.*"
  repository: https://prometheus-community.github.io/helm-charts
  condition: nodeExporter.enabled
