# Default values for prereqs-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

namespace: "dev-frontend"
 
podAnnotations: {}

ingress:
  enabled: true
  name: "frontend-ingress"
  namespace: "uat1-frontend"
  annotations: {
    kubernetes.io/ingress.class: "alb",
    alb.ingress.kubernetes.io/target-type: "instance",
    alb.ingress.kubernetes.io/scheme: "internet-facing",
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-2:858209661462:certificate/70376212-5316-42b4-95ba-99242539f12a",
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]',
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}',
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-2016-08",
    alb.ingress.kubernetes.io/wafv2-acl-arn: "arn:aws:wafv2:us-east-2:858209661462:regional/webacl/ion-dev-frontend-waf-acl/ba5456df-c9bd-4664-9348-b42cfaa9cbdc"
  }
  paths:
    - path: "/*"
      serviceName: "ssl-redirect"
      servicePort: "use-annotation"
    - path: "/api/*"
      serviceName: "frontend-service"
      servicePort: 80
    - path: "/*"
      serviceName: "frontend"
      servicePort: 80


nodeSelector: {}

tolerations: []

affinity: {}

## Subchart values
aws-load-balancer-controller:
  clusterName: "uat1-frontend-CLUSTER"
  region: "us-east-2"

kubernetes-dashboard:
  fullnameOverride: 'kubernetes-dashboard'